# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('drv_code', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=80, null=True, blank=True)),
                ('name_e', models.CharField(max_length=80, null=True, blank=True)),
                ('store_id', models.BigIntegerField(null=True, blank=True)),
                ('pcenter', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashArea',
            fields=[
                ('area_code', models.IntegerField(serialize=False, primary_key=True)),
                ('area_name', models.CharField(max_length=250, null=True, blank=True)),
            ],
            options={
                'db_table': 'cash_area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CashCustomers',
            fields=[
                ('cust_no', models.BigIntegerField(serialize=False, primary_key=True)),
                ('cust_tel', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_name', models.CharField(max_length=60, null=True, blank=True)),
                ('sector', models.CharField(max_length=20, null=True, blank=True)),
                ('gada', models.CharField(max_length=20, null=True, blank=True)),
                ('street', models.CharField(max_length=50, null=True, blank=True)),
                ('house', models.CharField(max_length=50, null=True, blank=True)),
                ('flat', models.CharField(max_length=20, null=True, blank=True)),
                ('floor', models.CharField(max_length=20, null=True, blank=True)),
                ('beside', models.CharField(max_length=50, null=True, blank=True)),
                ('cust_tel2', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_tel3', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_tel4', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_tel5', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_name_e', models.CharField(max_length=255, null=True, blank=True)),
                ('cardid', models.BigIntegerField(null=True, blank=True)),
                ('nat_no', models.BigIntegerField(null=True, blank=True)),
                ('has_card', models.NullBooleanField()),
                ('area_code2', models.BigIntegerField(null=True, blank=True)),
                ('sector2', models.CharField(max_length=20, null=True, blank=True)),
                ('gada2', models.CharField(max_length=20, null=True, blank=True)),
                ('street2', models.CharField(max_length=50, null=True, blank=True)),
                ('house2', models.CharField(max_length=50, null=True, blank=True)),
                ('flat2', models.CharField(max_length=50, null=True, blank=True)),
                ('floor2', models.CharField(max_length=50, null=True, blank=True)),
                ('beside2', models.CharField(max_length=50, null=True, blank=True)),
                ('area_code3', models.BigIntegerField(null=True, blank=True)),
                ('sector3', models.CharField(max_length=20, null=True, blank=True)),
                ('gada3', models.CharField(max_length=20, null=True, blank=True)),
                ('street3', models.CharField(max_length=50, null=True, blank=True)),
                ('house3', models.CharField(max_length=50, null=True, blank=True)),
                ('flat3', models.CharField(max_length=50, null=True, blank=True)),
                ('floor3', models.CharField(max_length=50, null=True, blank=True)),
                ('beside3', models.CharField(max_length=50, null=True, blank=True)),
                ('area_code4', models.BigIntegerField(null=True, blank=True)),
                ('sector4', models.CharField(max_length=20, null=True, blank=True)),
                ('gada4', models.CharField(max_length=20, null=True, blank=True)),
                ('street4', models.CharField(max_length=50, null=True, blank=True)),
                ('house4', models.CharField(max_length=50, null=True, blank=True)),
                ('flat4', models.CharField(max_length=50, null=True, blank=True)),
                ('floor4', models.CharField(max_length=50, null=True, blank=True)),
                ('beside4', models.CharField(max_length=50, null=True, blank=True)),
                ('area_code', models.ForeignKey(db_column=b'area_code', blank=True, to='localsync.CashArea', null=True)),
            ],
            options={
                'db_table': 'cash_customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CashDelivary',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('total', models.BigIntegerField(null=True, blank=True)),
                ('vdate', models.DateField(null=True, blank=True)),
                ('time_stamp', models.DateField(null=True, blank=True)),
                ('user_no', models.BigIntegerField(null=True, blank=True)),
                ('from_casher', models.CharField(max_length=100, null=True, blank=True)),
                ('to_cahser', models.CharField(max_length=100, null=True, blank=True)),
                ('notes', models.CharField(max_length=200, null=True, blank=True)),
                ('from_invoice', models.BigIntegerField(null=True, blank=True)),
                ('to_invoice', models.BigIntegerField(null=True, blank=True)),
                ('to_date', models.DateField(null=True, blank=True)),
                ('to_time', models.DateField(null=True, blank=True)),
                ('from_date', models.DateField(null=True, blank=True)),
                ('from_time', models.DateField(null=True, blank=True)),
            ],
            options={
                'db_table': 'cash_delivary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50, null=True, blank=True)),
                ('name_e', models.CharField(max_length=50, null=True, blank=True)),
                ('prods', models.BigIntegerField(null=True, blank=True)),
                ('cost_center', models.BigIntegerField(null=True, blank=True)),
                ('acc_branch', models.BigIntegerField(null=True, blank=True)),
                ('phone1', models.CharField(max_length=10, null=True, blank=True)),
                ('phone2', models.CharField(max_length=10, null=True, blank=True)),
                ('vaddress', models.CharField(max_length=200, null=True, blank=True)),
                ('phone', models.CharField(max_length=40, null=True, blank=True)),
                ('bnkcommaccno', models.BigIntegerField(null=True, blank=True)),
                ('cntr_salesqtycash', models.NullBooleanField()),
                ('cntr_salesqtycredit', models.NullBooleanField()),
                ('cntr_salesrqtycash', models.NullBooleanField()),
                ('cntr_salesrqtycredit', models.NullBooleanField()),
                ('cntr_sysdate', models.DateField(null=True, blank=True)),
                ('cntr_creditcustomer', models.BigIntegerField(null=True, blank=True)),
                ('cashsales_credit_acc', models.BigIntegerField(null=True, blank=True)),
                ('printer_nm', models.CharField(max_length=200, null=True, blank=True)),
                ('cntr_creditnoteacc', models.BigIntegerField(null=True, blank=True)),
                ('region', models.CharField(max_length=150, null=True, blank=True)),
                ('center_type', models.IntegerField(null=True, blank=True)),
                ('default_curr', models.IntegerField(null=True, blank=True)),
                ('logo_path', models.CharField(max_length=100, null=True, blank=True)),
                ('logo_blob', models.BinaryField(null=True, blank=True)),
                ('site_name', models.CharField(max_length=200, null=True, blank=True)),
                ('bnkcommaccno_old', models.CharField(max_length=40, null=True, blank=True)),
                ('cashsales_credit_acc_old', models.CharField(max_length=40, null=True, blank=True)),
                ('cntr_creditnoteacc_old', models.CharField(max_length=40, null=True, blank=True)),
                ('mgento_order', models.NullBooleanField()),
                ('fromcategory', models.FloatField(null=True, blank=True)),
                ('tocategory', models.FloatField(null=True, blank=True)),
                ('tablescreenwidth', models.FloatField(null=True, blank=True)),
                ('tablescreenheight', models.FloatField(null=True, blank=True)),
                ('loadandprintassemitem', models.BigIntegerField(null=True, blank=True)),
                ('logo2_path', models.CharField(max_length=100, null=True, blank=True)),
                ('logo3_path', models.CharField(max_length=100, null=True, blank=True)),
                ('logo2_blob', models.BinaryField(null=True, blank=True)),
                ('logo3_blob', models.BinaryField(null=True, blank=True)),
                ('closeorderprint', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'centers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.FloatField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=150, unique=True, null=True, blank=True)),
                ('cat1', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('cat2', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('caddress', models.CharField(max_length=400, null=True, blank=True)),
                ('tel1', models.CharField(max_length=100, null=True, blank=True)),
                ('tel2', models.CharField(max_length=100, null=True, blank=True)),
                ('fax', models.CharField(max_length=100, null=True, blank=True)),
                ('contact', models.CharField(max_length=100, null=True, blank=True)),
                ('credit_limit_flage', models.FloatField(null=True, blank=True)),
                ('credit_limit', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('credit_days', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('sales_man', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('accno', models.BigIntegerField(null=True, blank=True)),
                ('discount_code', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('name_e', models.CharField(max_length=150, null=True, blank=True)),
                ('tel4', models.CharField(max_length=100, null=True, blank=True)),
                ('jop', models.CharField(max_length=30, null=True, blank=True)),
                ('national', models.CharField(max_length=30, null=True, blank=True)),
                ('begin_date', models.DateField(null=True, blank=True)),
                ('notes', models.CharField(max_length=4000, null=True, blank=True)),
                ('cid', models.CharField(max_length=12, null=True, blank=True)),
                ('shoon', models.CharField(max_length=12, null=True, blank=True)),
                ('tarkhes', models.CharField(max_length=12, null=True, blank=True)),
                ('op_balance', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('balance', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('temp1', models.FloatField(null=True, blank=True)),
                ('temp2', models.FloatField(null=True, blank=True)),
                ('temp3', models.FloatField(null=True, blank=True)),
                ('temp4', models.FloatField(null=True, blank=True)),
                ('email', models.CharField(max_length=100, null=True, blank=True)),
                ('web_page', models.CharField(max_length=100, null=True, blank=True)),
                ('temp_date', models.DateField(null=True, blank=True)),
                ('temp_date2', models.DateField(null=True, blank=True)),
                ('credit_days_flage', models.IntegerField(null=True, blank=True)),
                ('cost_center', models.DecimalField(null=True, max_digits=20, decimal_places=5, blank=True)),
                ('to_dt', models.DateField(null=True, blank=True)),
                ('date_flage', models.IntegerField(null=True, blank=True)),
                ('discount_ratio', models.DecimalField(null=True, max_digits=6, decimal_places=3, blank=True)),
                ('area_code', models.CharField(max_length=20, null=True, blank=True)),
                ('sector', models.CharField(max_length=20, null=True, blank=True)),
                ('gada', models.CharField(max_length=20, null=True, blank=True)),
                ('street', models.CharField(max_length=50, null=True, blank=True)),
                ('house', models.CharField(max_length=50, null=True, blank=True)),
                ('flat', models.CharField(max_length=20, null=True, blank=True)),
                ('floor', models.CharField(max_length=20, null=True, blank=True)),
                ('isbranch', models.NullBooleanField()),
                ('inst_acceptlessthanminval', models.NullBooleanField()),
                ('ob_balance_f', models.DecimalField(null=True, max_digits=22, decimal_places=4, blank=True)),
                ('ob_balance_curr', models.IntegerField(null=True, blank=True)),
                ('cust_manid', models.CharField(max_length=20, null=True, blank=True)),
                ('section', models.IntegerField(null=True, blank=True)),
                ('is_stop', models.BigIntegerField(null=True, blank=True)),
                ('stop_date', models.DateField(null=True, blank=True)),
                ('stop_reason', models.CharField(max_length=150, null=True, blank=True)),
                ('stop_user', models.CharField(max_length=100, null=True, blank=True)),
                ('route', models.IntegerField(null=True, blank=True)),
                ('account_id', models.BigIntegerField(null=True, blank=True)),
                ('accno_old', models.CharField(max_length=40, null=True, blank=True)),
                ('caddress2', models.CharField(max_length=400, null=True, blank=True)),
                ('caddress3', models.CharField(max_length=400, null=True, blank=True)),
                ('caddress4', models.CharField(max_length=400, null=True, blank=True)),
                ('pcenter', models.ForeignKey(db_column=b'pcenter', blank=True, to='localsync.Centers', null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Issue1',
            fields=[
                ('code', models.IntegerField()),
                ('vdate', models.DateField(null=True, blank=True)),
                ('pur_order', models.CharField(max_length=30, null=True, blank=True)),
                ('qutaion', models.BigIntegerField(null=True, blank=True)),
                ('payment', models.IntegerField(null=True, blank=True)),
                ('customer_data', models.CharField(max_length=100, null=True, blank=True)),
                ('customer_name', models.CharField(max_length=800, null=True, blank=True)),
                ('user_no', models.BigIntegerField(null=True, blank=True)),
                ('time_stamp', models.DateField()),
                ('notes_print_falge', models.NullBooleanField()),
                ('bilno', models.BigIntegerField(serialize=False, primary_key=True)),
                ('templet', models.NullBooleanField()),
                ('rev_ok', models.NullBooleanField()),
                ('layaway', models.NullBooleanField()),
                ('deli_date', models.DateField(null=True, blank=True)),
                ('payed', models.DecimalField(null=True, max_digits=15, decimal_places=3, blank=True)),
                ('payed1', models.DecimalField(null=True, max_digits=15, decimal_places=3, blank=True)),
                ('payed2', models.DecimalField(null=True, max_digits=15, decimal_places=3, blank=True)),
                ('pay_ok', models.NullBooleanField()),
                ('reset_bilno', models.BigIntegerField(null=True, blank=True)),
                ('step1', models.NullBooleanField()),
                ('step2', models.NullBooleanField()),
                ('step3', models.NullBooleanField()),
                ('step4', models.NullBooleanField()),
                ('from_type', models.IntegerField(null=True, blank=True)),
                ('note6', models.CharField(max_length=100, null=True, blank=True)),
                ('note7', models.CharField(max_length=100, null=True, blank=True)),
                ('driver_name', models.CharField(max_length=60, null=True, blank=True)),
                ('car_no', models.CharField(max_length=20, null=True, blank=True)),
                ('leave_time', models.DateField(null=True, blank=True)),
                ('note1', models.CharField(max_length=40, null=True, blank=True)),
                ('note2', models.CharField(max_length=40, null=True, blank=True)),
                ('note3', models.CharField(max_length=40, null=True, blank=True)),
                ('note4', models.CharField(max_length=40, null=True, blank=True)),
                ('note5', models.CharField(max_length=40, null=True, blank=True)),
                ('vtime', models.DateField(null=True, blank=True)),
                ('hand_time', models.DateField(null=True, blank=True)),
                ('return_time', models.DateField(null=True, blank=True)),
                ('step5', models.NullBooleanField()),
                ('recieved_flage', models.NullBooleanField()),
                ('area_code', models.CharField(max_length=20, null=True, blank=True)),
                ('sector', models.CharField(max_length=30, null=True, blank=True)),
                ('gada', models.CharField(max_length=30, null=True, blank=True)),
                ('street', models.CharField(max_length=30, null=True, blank=True)),
                ('house', models.CharField(max_length=30, null=True, blank=True)),
                ('flat', models.CharField(max_length=30, null=True, blank=True)),
                ('floor', models.CharField(max_length=30, null=True, blank=True)),
                ('cust_tel', models.CharField(max_length=20, null=True, blank=True)),
                ('bnkcomm', models.FloatField(null=True, blank=True)),
                ('payment2', models.DecimalField(null=True, max_digits=10, decimal_places=3, blank=True)),
                ('payment3', models.DecimalField(null=True, max_digits=10, decimal_places=3, blank=True)),
                ('p_date1', models.DateField(null=True, blank=True)),
                ('p_date2', models.DateField(null=True, blank=True)),
                ('p_date3', models.DateField(null=True, blank=True)),
                ('visit_no', models.CharField(max_length=10, null=True, blank=True)),
                ('temp_date', models.DateField(null=True, blank=True)),
                ('tel', models.CharField(max_length=20, null=True, blank=True)),
                ('prod_id', models.BigIntegerField(null=True, blank=True)),
                ('equipment_code', models.CharField(max_length=10, null=True, blank=True)),
                ('f11_payed', models.FloatField(null=True, blank=True)),
                ('costcenter_id', models.BigIntegerField(null=True, blank=True)),
                ('xcode', models.IntegerField(null=True, blank=True)),
                ('curr_id', models.BigIntegerField(null=True, blank=True)),
                ('curr_rate', models.DecimalField(null=True, max_digits=15, decimal_places=7, blank=True)),
                ('cont_equipment_code', models.CharField(max_length=10, null=True, blank=True)),
                ('sec_id', models.IntegerField(null=True, blank=True)),
                ('sec_center', models.BigIntegerField(null=True, blank=True)),
                ('km_count', models.DecimalField(null=True, max_digits=18, decimal_places=3, blank=True)),
                ('jop_no', models.CharField(max_length=30, null=True, blank=True)),
                ('cust_phone1', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_phone2', models.CharField(max_length=20, null=True, blank=True)),
                ('cust_add', models.CharField(max_length=200, null=True, blank=True)),
                ('cust_ref', models.CharField(max_length=200, null=True, blank=True)),
                ('cust_resp', models.CharField(max_length=100, null=True, blank=True)),
                ('printingtimes', models.IntegerField(null=True, blank=True)),
                ('total_act_catalog_weight', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('total_price', models.DecimalField(null=True, max_digits=20, decimal_places=3, blank=True)),
                ('add_voucher_user', models.CharField(max_length=16, null=True, blank=True)),
                ('lupdate_voucher_user', models.CharField(max_length=16, null=True, blank=True)),
                ('inv_type', models.NullBooleanField()),
                ('shift_id', models.BigIntegerField(null=True, blank=True)),
                ('inv1', models.BigIntegerField(null=True, blank=True)),
                ('inv2', models.BigIntegerField(null=True, blank=True)),
                ('engineer_commission', models.FloatField(null=True, blank=True)),
                ('engineer_id', models.BigIntegerField(null=True, blank=True)),
                ('manager_commission', models.FloatField(null=True, blank=True)),
                ('manager_id', models.BigIntegerField(null=True, blank=True)),
                ('salesman_commission', models.FloatField(null=True, blank=True)),
                ('delivary_method_id', models.BigIntegerField(null=True, blank=True)),
                ('form_no', models.BigIntegerField(null=True, blank=True)),
                ('print_ok', models.BigIntegerField(null=True, blank=True)),
                ('sales_commm', models.FloatField(null=True, blank=True)),
                ('accept_user', models.CharField(max_length=16, null=True, blank=True)),
                ('account_item_code', models.BigIntegerField(null=True, blank=True)),
                ('purchase_order_no', models.BigIntegerField(null=True, blank=True)),
                ('purchase_order_date', models.DateField(null=True, blank=True)),
                ('auto_issue', models.NullBooleanField()),
                ('round_figure', models.FloatField(null=True, blank=True)),
                ('notes', models.CharField(max_length=4000, null=True, blank=True)),
                ('order_stat', models.CharField(max_length=255, null=True, blank=True)),
                ('machine_no', models.FloatField(null=True, blank=True)),
                ('insur_remaining_amt', models.DecimalField(null=True, max_digits=22, decimal_places=6, blank=True)),
                ('insur_rem', models.DecimalField(null=True, max_digits=22, decimal_places=6, blank=True)),
                ('price_type', models.NullBooleanField()),
                ('price_code', models.BigIntegerField(null=True, blank=True)),
                ('depr_accno', models.CharField(max_length=14, null=True, blank=True)),
                ('cashcredit_type', models.CharField(max_length=25, null=True, blank=True)),
                ('total_cur', models.DecimalField(null=True, max_digits=22, decimal_places=8, blank=True)),
                ('total', models.DecimalField(null=True, max_digits=22, decimal_places=8, blank=True)),
                ('discount', models.DecimalField(null=True, max_digits=22, decimal_places=8, blank=True)),
                ('discount_cur', models.DecimalField(null=True, max_digits=22, decimal_places=8, blank=True)),
                ('performa_bilno', models.BigIntegerField(null=True, blank=True)),
                ('performa_pcenter', models.BigIntegerField(null=True, blank=True)),
                ('cardid', models.BigIntegerField(null=True, blank=True)),
                ('isrestaurant', models.FloatField(null=True, blank=True)),
                ('rst_paid', models.FloatField(null=True, blank=True)),
                ('rst_remain', models.FloatField(null=True, blank=True)),
                ('order_type', models.NullBooleanField()),
                ('rst_shift_id', models.BigIntegerField(null=True, blank=True)),
                ('tableid', models.FloatField(null=True, blank=True)),
                ('iscocked', models.NullBooleanField()),
                ('floorid', models.FloatField(null=True, blank=True)),
                ('sectionid', models.FloatField(null=True, blank=True)),
                ('addressid', models.BigIntegerField(null=True, blank=True)),
                ('driver_name_e', models.CharField(max_length=60, null=True, blank=True)),
                ('orderstateno', models.FloatField(null=True, blank=True)),
                ('latereasoncode', models.BigIntegerField(null=True, blank=True)),
                ('discountpercentage', models.DecimalField(null=True, max_digits=12, decimal_places=8, blank=True)),
                ('orderid', models.BigIntegerField(null=True, blank=True)),
                ('discount_1', models.FloatField(null=True, blank=True)),
                ('discount_c', models.FloatField(null=True, blank=True)),
                ('coupontypes_no', models.FloatField(null=True, blank=True)),
                ('coupontypes_id', models.FloatField(null=True, blank=True)),
                ('discount_v', models.FloatField(null=True, blank=True)),
                ('void', models.FloatField(null=True, blank=True)),
                ('void_items_balance', models.FloatField(null=True, blank=True)),
                ('cash_delivary', models.ForeignKey(blank=True, to='localsync.CashDelivary', null=True)),
                ('cust_no', models.ForeignKey(db_column=b'cust_no', blank=True, to='localsync.CashCustomers', null=True)),
                ('custno', models.ForeignKey(db_column=b'custno', blank=True, to='localsync.Customers', null=True)),
                ('drv_code', models.ForeignKey(db_column=b'drv_code', blank=True, to='localsync.Drivers', null=True)),
                ('pcenter', models.ForeignKey(to='localsync.Centers', db_column=b'pcenter')),
            ],
            options={
                'db_table': 'issue_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50, null=True, blank=True)),
                ('name_e', models.CharField(max_length=50, null=True, blank=True)),
            ],
            options={
                'db_table': 'payment_terms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesMen',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50, null=True, blank=True)),
                ('name_e', models.CharField(max_length=50, null=True, blank=True)),
                ('acc_branch', models.DecimalField(null=True, max_digits=20, decimal_places=5, blank=True)),
                ('commission', models.DecimalField(null=True, max_digits=20, decimal_places=5, blank=True)),
                ('pwd', models.CharField(max_length=100, null=True, blank=True)),
                ('accno', models.BigIntegerField(null=True, blank=True)),
                ('guardship_accno', models.BigIntegerField(null=True, blank=True)),
                ('sort_id', models.FloatField(null=True, blank=True)),
                ('e_mail', models.CharField(max_length=100, null=True, blank=True)),
                ('jop_position', models.CharField(max_length=100, null=True, blank=True)),
                ('phone', models.CharField(max_length=100, null=True, blank=True)),
                ('alt_sman', models.ForeignKey(db_column=b'alt_sman', blank=True, to='localsync.SalesMen', null=True)),
                ('pcenter', models.ForeignKey(db_column=b'pcenter', blank=True, to='localsync.Centers', null=True)),
            ],
            options={
                'db_table': 'sales_men',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='issue1',
            name='salesman',
            field=models.ForeignKey(related_name='salesman', blank=True, to='localsync.SalesMen', null=True),
        ),
        migrations.AddField(
            model_name='issue1',
            name='sman',
            field=models.ForeignKey(related_name='sman', db_column=b'sman', blank=True, to='localsync.SalesMen', null=True),
        ),
        migrations.AddField(
            model_name='issue1',
            name='terms',
            field=models.ForeignKey(db_column=b'terms', blank=True, to='localsync.PaymentTerms', null=True),
        ),
        migrations.AddField(
            model_name='centers',
            name='sman',
            field=models.ForeignKey(db_column=b'sman', blank=True, to='localsync.SalesMen', null=True),
        ),
        migrations.AddField(
            model_name='cashdelivary',
            name='pcenter',
            field=models.ForeignKey(to='localsync.Centers', db_column=b'pcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='issue1',
            unique_together=set([('code', 'pcenter', 'bilno')]),
        ),
        migrations.AlterUniqueTogether(
            name='cashdelivary',
            unique_together=set([('id', 'pcenter')]),
        ),
    ]
